### ISSUE TITLE
Compile activate against scala 2.11

### ISSUE THREAD

**Issue by arjunsol** [fwbrasil/activate#148]
I'd like to use activate but it's not an option for us as so many other dependencies require 2.11

**Comment by avramirez** [comment]
It still supports 2.10? The v1.7?

**Comment by fwbrasil** [comment]
Yep. :)

http://search.maven.org/#search%7Cga%7C1%7Cactivate

**Comment by Alain-Bearez** [comment]
The pull request I submitted (https://github.com/fwbrasil/activate/pull/165)
does a cross compilation for both Scala 2.10 (which was no more supported
starting with Activate 1.7) and Scala 2.11 since we need the latest bug
fixes from 1.7 running with older Scala.

2015-01-07 12:21 GMT-03:00 Andrew James V. Ramirez <notifications@github.com
