### ISSUE TITLE
first access is very slow

### ISSUE THREAD

**Issue by kanekv** [fwbrasil/activate#149]
When i try to access database for the first time it takes a lot of time to initialize:
Reflections took 1945 ms to scan 2 urls, producing 43 keys and 805 values
Reflections took 1103 ms to scan 4 urls, producing 158 keys and 3581 values
Initializing live cache for context Connection
Initializing context Connection

Is there a way to improve it or at least make it non-lazy, so it initializes right after start?
What's the best approach to make development cycle faster, it's pretty frustrating to wait several seconds every time after reload

**Comment by frossi85** [comment]
I have been experimenting the same problem, because I am a little new in scala world I thought that the problem was a scala compiler performance issue. But then I detect that the source is the issue described here. My project is a Play application with around 25 entities and a lot of play html templates. Perhaps this issue is not a problem in a microservice arquitecture.

You have a way to measure the source of it. It could be the scanning/searching of classes that are Entity or is more the use of reflection in each of those entities??

Could you gave me a pointer to the class that makes the inicialization??
