### ISSUE TITLE
Is it possible to control the isolation level with database transactions?

### ISSUE THREAD

**Issue by metatron-the-chronicler** [fwbrasil/activate#166]
Is it possible when working with a jdbc based connection to MS SQL Server to create a transaction and set the isolation level, to read uncommitted for example?

**Comment by fwbrasil** [comment]
@metatron-the-chronicler Please use the google groups or gitter room for these kind of questions.
Could you explain why you would need to change the isolation level? There isn't a 1-1 relation between Activate transactions and database transactions, since they are run in-memory and use a database transaction only during commit time.

**Comment by metatron-the-chronicler** [comment]
Some systems I work with need to be accessed with the nolock hint which is the equivalent of running a select statement inside a transaction with the isolation level set to read uncommitted. I'll be sure to use the ML in the future as requested.

**Comment by fwbrasil** [comment]
@metatron-the-chronicler Activate already uses a lower isolation level for reads[0] and the cache allows to run read-only transactions without touching the database if the entity is already in-memory. Would this behavior be sufficient?

[0] https://github.com/fwbrasil/activate/blob/master/activate-jdbc/src/main/scala/net/fwbrasil/activate/storage/relational/PreparedStatementCache.scala#L30
